apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: femattos/apicloud:latest
        command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: postgres.app.svc.cluster.local # Host do banco corrigido
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: NOME_DO_BANCO
        - name: POSTGRES_USER
          value: SEUUSUARIO
        - name: POSTGRES_PASSWORD
          value: SUASENHA
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: app
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
