name: app

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-projeto}  # Variável de ambiente com valor padrão 'projeto'
      POSTGRES_USER: ${POSTGRES_USER:-projeto}  # Usuário padrão 'projeto'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projeto}  # Senha padrão 'projeto'
    ports:
      - 5432:5432  # Mapeamento da porta 5432 para o host (opcional, depende da necessidade)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume para persistência dos dados
    networks:
      - app-network

  # Serviço da API FastAPI
  api:
    image: femattos/apicloud:latest  # Nome e tag da imagem
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

# Definição do volume para persistir os dados do banco de dados
volumes:
  postgres_data:

# Rede de comunicação entre os contêineres
networks:
  app-network:
